services:
  - type: web
    name: pharma-cloud-erp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: (python init_prod.py || true) && gunicorn -b 0.0.0.0:$PORT --timeout 120 run:app
    envVars:
      - key: FLASK_APP
        value: manage.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: pharma-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_TYPE
        value: sqlalchemy

databases:
  - name: pharma-db
    plan: free
