"""Expansion SaaS : Ajout des colonnes multi-tenant

Revision ID: c50e0760c9b2
Revises: f16f4d043755
Create Date: 2026-04-07 11:38:35.378659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50e0760c9b2'
down_revision = 'f16f4d043755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('purchase_price', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('salary_advances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('time_clocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pharmacy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pharmacies', ['pharmacy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('time_clocks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('description')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('salary_advances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('payroll_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('purchase_price')
        batch_op.drop_column('pharmacy_id')

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pharmacy_id')

    # ### end Alembic commands ###
