"""Initial migration

Revision ID: f16f4d043755
Revises: 
Create Date: 2026-04-07 00:10:40.686417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16f4d043755'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dark_mode')
        batch_op.drop_column('theme_color')
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('theme_color', sa.VARCHAR(length=20), server_default=sa.text("'#0d6efd'"), nullable=True))
        batch_op.add_column(sa.Column('dark_mode', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True))

    # ### end Alembic commands ###
